camping           = "Camping"
caravan_heritage  = "Caravan Heritage"
fishing           = "Fishing"
picnicing         = "Picnicing"
pet_friendly      = "Pet friendly"
landmarks         = "Landmarks"
huts_and_shelters = "Huts and shelters"
leisure           = "Leisure"
places_of_worship = "Places of worship"
wildlife          = "Wildlife"
unknown           = "Unkown"

CONVERSION_MAP = {
  "Transport"                                       => landmarks,
  "Railway Station"                                 => landmarks,
  "Mixed Use"                                       => leisure,
  "Retail/Office/Carpark"                           => huts_and_shelters,
  "Place Of Assembly"                               => landmarks,
  "Library"                                         => leisure,
  "Leisure/Recreation"                              => leisure,
  "Informal Outdoor Facility (Park/Garden/Reserve)" => leisure,
  "Place of Worship"                                => places_of_worship,
  "Church"                                          => places_of_worship,
  "Health Services"                                 => landmarks,
  "Private Hospital"                                => landmarks,
  "Synagogue"                                       => places_of_worship,
  "Community Use"                                   => landmarks,
  "Police Station"                                  => landmarks,
  "Visitor Centre"                                  => landmarks,
  "Major Sports & Recreation Facility"              => leisure,
  "Transport Terminal"                              => landmarks,
  "Private Sports Club/Facility"                    => leisure,
  "Cemetery"                                        => landmarks,
  "Retail"                                          => leisure,
  "Education Centre"                                => landmarks,
  "Primary Schools"                                 => landmarks,
  "Art Gallery/Museum"                              => leisure,
  "Secondary Schools"                               => landmarks,
  "School - Primary and Secondary Education"        => landmarks,
  "Theatre Live"                                    => leisure,
  "Tertiary (University)"                           => landmarks,
  "Public Buildings"                                => huts_and_shelters,
  "Retail/Office"                                   => huts_and_shelters,
  "Office"                                          => huts_and_shelters,
  "Government Building"                             => landmarks,
  "Outdoor Recreation Facility (Zoo, Golf Course)"  => leisure,
  "Function/Conference/Exhibition Centre"           => leisure,
  "Vacant Land"                                     => huts_and_shelters,
  "Vacant Land - Undeveloped Site"                  => huts_and_shelters,
  "Purpose Built"                                   => landmarks,
  "Casino"                                          => leisure,
  "Public Hospital"                                 => landmarks,
  "Film & RV Studio"                                => leisure,
  "Current Construction Site"                       => landmarks,
  "Marina"                                          => leisure,
  "Observation Tower/Wheel"                         => landmarks,
  "Further Education"                               => landmarks,
  "Specialist Residential Accommodation"            => huts_and_shelters,
  "Hostel"                                          => huts_and_shelters,
  "Current Construction Site - Commercial"          => landmarks,
  "Cinema"                                          => leisure,
  "Indoor Recreation Facility"                      => leisure,
  "Residential Accommodation"                       => huts_and_shelters,
  "Dwelling (House)"                                => huts_and_shelters,
  "Industrial"                                      => unknown,
  "Industrial (Manufacturing)"                      => unknown,
  "Warehouse/Store"                                 => huts_and_shelters,
  "Store Yard"                                      => landmarks,
  "Fire Station"                                    => landmarks,
  "Retail/Office/Residential/Carpark"               => leisure,
  "Gymnasium/Health Club"                           => leisure,
  "Aquarium"                                        => leisure,
  "Retail/Residential"                              => leisure,
  "Bridge"                                          => landmarks,
  "Department Store"                                => leisure,
  "Medical Services"                                => landmarks
}
